services:
  - type: web
    name: telegram-gpt-bot
    runtime: python
    plan: free
    pythonVersion: 3.11         # impose l’utilisation de Python 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
